[build]
builder = "DOCKER"
dockerfilePath = "Dockerfile"

[build.variables]
DOTNET_GENERATE_ASPNET_CERTIFICATE = "false"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"