// <auto-generated />
using System;
using ChoNaBojo.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChoNaBojo.Server.Migrations
{
    [DbContext(typeof(ChoNaBojoContext))]
    [Migration("20260718111643_MakeRefreshTokenHashUnique")]
    partial class MakeRefreshTokenHashUnique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChoNaBojo.Server.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConsumedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ChoNaBojo.Server.Data.Entities.Sport", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "football",
                            Name = "Piłka nożna"
                        },
                        new
                        {
                            Id = 2,
                            Code = "basketball",
                            Name = "Koszykówka"
                        },
                        new
                        {
                            Id = 3,
                            Code = "volleyball",
                            Name = "Siatkówka"
                        },
                        new
                        {
                            Id = 4,
                            Code = "tennis",
                            Name = "Tenis"
                        },
                        new
                        {
                            Id = 5,
                            Code = "running",
                            Name = "Bieganie"
                        },
                        new
                        {
                            Id = 6,
                            Code = "cycling",
                            Name = "Kolarstwo"
                        },
                        new
                        {
                            Id = 7,
                            Code = "rollerblading",
                            Name = "Jazda na rolkach"
                        },
                        new
                        {
                            Id = 8,
                            Code = "gym",
                            Name = "Siłownia"
                        },
                        new
                        {
                            Id = 9,
                            Code = "street_workout",
                            Name = "Street workout"
                        },
                        new
                        {
                            Id = 10,
                            Code = "swimming",
                            Name = "Pływanie"
                        });
                });

            modelBuilder.Entity("ChoNaBojo.Server.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CommunicatorHandle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("CommunicatorPlatform")
                        .HasColumnType("integer");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LoginEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("NormalizedLoginEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedLoginEmail")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_CommunicatorPlatform", "\"CommunicatorPlatform\" IS NULL OR \"CommunicatorPlatform\" IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_Users_ContactMethod", "(\r\n	(NULLIF(BTRIM(\"ContactPhone\"), '') IS NOT NULL)\r\n	OR (NULLIF(BTRIM(\"ContactEmail\"), '') IS NOT NULL)\r\n	OR (\"CommunicatorPlatform\" IS NOT NULL AND NULLIF(BTRIM(\"CommunicatorHandle\"), '') IS NOT NULL)\r\n)\r\nAND\r\n(\r\n	(\"CommunicatorPlatform\" IS NULL AND NULLIF(BTRIM(\"CommunicatorHandle\"), '') IS NULL)\r\n	OR (\"CommunicatorPlatform\" IS NOT NULL AND NULLIF(BTRIM(\"CommunicatorHandle\"), '') IS NOT NULL)\r\n)");
                        });
                });

            modelBuilder.Entity("ChoNaBojo.Server.Data.Entities.Venue", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("ChoNaBojo.Server.Data.Entities.VenueSport", b =>
                {
                    b.Property<int>("VenueId")
                        .HasColumnType("integer");

                    b.Property<int>("SportId")
                        .HasColumnType("integer");

                    b.HasKey("VenueId", "SportId");

                    b.HasIndex("SportId");

                    b.ToTable("VenueSports");
                });

            modelBuilder.Entity("ChoNaBojo.Server.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("ChoNaBojo.Server.Data.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChoNaBojo.Server.Data.Entities.VenueSport", b =>
                {
                    b.HasOne("ChoNaBojo.Server.Data.Entities.Sport", "Sport")
                        .WithMany("VenueSports")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChoNaBojo.Server.Data.Entities.Venue", "Venue")
                        .WithMany("VenueSports")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("ChoNaBojo.Server.Data.Entities.Sport", b =>
                {
                    b.Navigation("VenueSports");
                });

            modelBuilder.Entity("ChoNaBojo.Server.Data.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("ChoNaBojo.Server.Data.Entities.Venue", b =>
                {
                    b.Navigation("VenueSports");
                });
#pragma warning restore 612, 618
        }
    }
}
