// <auto-generated />
using ChoNaBojo.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChoNaBojo.Server.Migrations
{
    [DbContext(typeof(ChoNaBojoContext))]
    partial class ChoNaBojoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChoNaBojo.Server.Data.Entities.Sport", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "football",
                            Name = "Piłka nożna"
                        },
                        new
                        {
                            Id = 2,
                            Code = "basketball",
                            Name = "Koszykówka"
                        },
                        new
                        {
                            Id = 3,
                            Code = "volleyball",
                            Name = "Siatkówka"
                        },
                        new
                        {
                            Id = 4,
                            Code = "tennis",
                            Name = "Tenis"
                        },
                        new
                        {
                            Id = 5,
                            Code = "running",
                            Name = "Bieganie"
                        },
                        new
                        {
                            Id = 6,
                            Code = "cycling",
                            Name = "Kolarstwo"
                        },
                        new
                        {
                            Id = 7,
                            Code = "rollerblading",
                            Name = "Jazda na rolkach"
                        },
                        new
                        {
                            Id = 8,
                            Code = "gym",
                            Name = "Siłownia"
                        },
                        new
                        {
                            Id = 9,
                            Code = "street_workout",
                            Name = "Street workout"
                        },
                        new
                        {
                            Id = 10,
                            Code = "swimming",
                            Name = "Pływanie"
                        });
                });

            modelBuilder.Entity("ChoNaBojo.Server.Data.Entities.Venue", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("ChoNaBojo.Server.Data.Entities.VenueSport", b =>
                {
                    b.Property<int>("VenueId")
                        .HasColumnType("integer");

                    b.Property<int>("SportId")
                        .HasColumnType("integer");

                    b.HasKey("VenueId", "SportId");

                    b.HasIndex("SportId");

                    b.ToTable("VenueSports");
                });

            modelBuilder.Entity("ChoNaBojo.Server.Data.Entities.VenueSport", b =>
                {
                    b.HasOne("ChoNaBojo.Server.Data.Entities.Sport", "Sport")
                        .WithMany("VenueSports")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChoNaBojo.Server.Data.Entities.Venue", "Venue")
                        .WithMany("VenueSports")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("ChoNaBojo.Server.Data.Entities.Sport", b =>
                {
                    b.Navigation("VenueSports");
                });

            modelBuilder.Entity("ChoNaBojo.Server.Data.Entities.Venue", b =>
                {
                    b.Navigation("VenueSports");
                });
#pragma warning restore 612, 618
        }
    }
}
